version: '3'

services:
  postgres:
    image: postgres:15
    container_name: agent_postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: agent_calendar
    ports:
      - 5432:5432
    volumes:
      - .docker/postgres:/var/lib/postgresql/data
