// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/freitasmatheusrn/agent-calendar/configs"
	"github.com/freitasmatheusrn/agent-calendar/internal/infra/database"
	"github.com/freitasmatheusrn/agent-calendar/internal/infra/server/handlers"
	"net/http"
)

import (
	_ "github.com/joho/godotenv/autoload"
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

func InitializeServer() (*http.Server, error) {
	string2 := configs.ProvideConfigPath()
	config, err := configs.LoadConfig(string2)
	if err != nil {
		return nil, err
	}
	db, err := database.NewDB(config)
	if err != nil {
		return nil, err
	}
	userRepository := database.NewUserRepository(db)
	userHandler := handlers.NewUserHandler(userRepository)
	handlersHandlers := handlers.NewHandlers(userHandler)
	server := NewServer(config, db, handlersHandlers)
	return server, nil
}
